/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.escola.view;


import br.com.controller.ProfessorController;
import br.com.modelo.negocio.Professor;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Usuário
 */
public class EditarProfessores extends javax.swing.JFrame {
 
    int linhaSelecionada;
    int codigoProfessor;
    ProfessorTableModel model;
    
    
    /**
     * Creates new form CadastrarProfessores
     */
    public EditarProfessores(int selecionado, int cdProfessor, ProfessorTableModel mtb) {
        initComponents();
        campoCodigo.setEditable(false);
        linhaSelecionada = selecionado;
        cdProfessor = cdProfessor;
        model = mtb;



        ProfessorController mc = new ProfessorController();
        Professor f = new Professor();
        f = mc.listarProfessorById(cdProfessor);

      
        campoCodigo.setText(Integer.toString(f.getCodigo()));
       
        campoNome.setText(f.getNome());
        String s;
        String m = "Masculino";
        String f1 = "Feminino";
        s = f.getSexo();
        if(s.equals(m)){
        rbMasculino.setSelected(true);
        }else{
            rbFeminino.setSelected(true);
        }   
     
        campoTelefone.setText(f.getTelefone());
        campoCelular.setText(f.getCelular());
        campoEmail.setText(f.getEmail());
         compoDisciplina.setText(f.getDisciplina());
       

       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        rbMasculino = new javax.swing.JRadioButton();
        rbFeminino = new javax.swing.JRadioButton();
        campoCelular = new javax.swing.JFormattedTextField();
        campoTelefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        campoEmail = new javax.swing.JTextField();
        Disiplina = new javax.swing.JLabel();
        compoDisciplina = new javax.swing.JTextField();
        BotaoSalvar = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Professores");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Código");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 140, 60, 20);

        campoCodigo.setEditable(false);
        campoCodigo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        campoCodigo.setToolTipText("Digite o nome do usuário");
        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(campoCodigo);
        campoCodigo.setBounds(50, 170, 120, 30);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Nome");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 210, 60, 20);

        campoNome.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        campoNome.setToolTipText("Digite o nome do usuário");
        campoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNomeActionPerformed(evt);
            }
        });
        jPanel1.add(campoNome);
        campoNome.setBounds(50, 240, 450, 30);

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel11.setText("Sexo");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(50, 280, 190, 20);

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel19.setText("Telefone");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(280, 280, 130, 20);

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel21.setText("Celular");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(460, 280, 160, 20);

        rbMasculino.setBackground(new java.awt.Color(255, 255, 255));
        rbMasculino.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        rbMasculino.setText("Masculino");
        rbMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMasculinoActionPerformed(evt);
            }
        });
        jPanel1.add(rbMasculino);
        rbMasculino.setBounds(50, 310, 93, 27);

        rbFeminino.setBackground(new java.awt.Color(255, 255, 255));
        rbFeminino.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        rbFeminino.setText("Feminino");
        rbFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemininoActionPerformed(evt);
            }
        });
        jPanel1.add(rbFeminino);
        rbFeminino.setBounds(150, 310, 93, 27);

        try {
            campoCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCelularActionPerformed(evt);
            }
        });
        jPanel1.add(campoCelular);
        campoCelular.setBounds(460, 310, 150, 30);

        try {
            campoTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #### - ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTelefoneActionPerformed(evt);
            }
        });
        jPanel1.add(campoTelefone);
        campoTelefone.setBounds(280, 310, 150, 30);

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel10.setText("Email");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(50, 350, 50, 20);

        campoEmail.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        campoEmail.setToolTipText("Digite o nome do usuário");
        campoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoEmailActionPerformed(evt);
            }
        });
        jPanel1.add(campoEmail);
        campoEmail.setBounds(50, 380, 260, 30);

        Disiplina.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        Disiplina.setText("Disciplina");
        jPanel1.add(Disiplina);
        Disiplina.setBounds(50, 420, 90, 20);
        jPanel1.add(compoDisciplina);
        compoDisciplina.setBounds(50, 450, 200, 30);

        BotaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/isequiel/view/imagens/SalvarUsuario.png"))); // NOI18N
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(BotaoSalvar);
        BotaoSalvar.setBounds(690, 360, 100, 90);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Salvar");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(710, 460, 90, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel4.setText("Cadastrar Professores");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(320, 40, 340, 42);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoActionPerformed

    private void campoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNomeActionPerformed

    private void rbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMasculinoActionPerformed

    private void rbFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFemininoActionPerformed

    private void campoCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCelularActionPerformed

    private void campoTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTelefoneActionPerformed

    private void campoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoEmailActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
       Professor f = new Professor();
       
        f.setNome(campoNome.getText());
        if (rbMasculino.isSelected()) {
            f.setSexo("Masculino");
        }
        if (rbFeminino.isSelected()) {
            f.setSexo("Feminino");
        }
        f.setTelefone(campoTelefone.getText());
        f.setCelular(campoCelular.getText());
        f.setEmail(campoEmail.getText());
        f.setDisciplina(compoDisciplina.getText());
        f.setCodigo(Integer.parseInt(campoCodigo.getText()));
        
        ProfessorController mc = new ProfessorController();
            if (mc.salvar(f)){
            model.updateProfessor(linhaSelecionada, f);
            }
            dispose();
       
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotaoSalvar;
    private javax.swing.JLabel Disiplina;
    private javax.swing.JFormattedTextField campoCelular;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoEmail;
    private javax.swing.JTextField campoNome;
    private javax.swing.JFormattedTextField campoTelefone;
    private javax.swing.JTextField compoDisciplina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMasculino;
    // End of variables declaration//GEN-END:variables
}
