/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.escola.view;

import br.com.controller.LaboratorioController;
import br.com.controller.ProfessorController;
import br.com.modelo.negocio.Laboratorio;
import br.com.modelo.negocio.Professor;
import com.sun.org.apache.bcel.internal.generic.Select;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Usuário
 */
public class EditarReservaLaboratorio extends javax.swing.JFrame {

    int linhaSelecionada;
    int codigoLaboratorio;
    LaboratorioTableModel model;
    
    /**
     * Creates new form ReservaLaboratorio
     */
    public EditarReservaLaboratorio(int selecionado, int cdLaboratorio, LaboratorioTableModel mtb) {
        initComponents();
        campoCodigo.setEditable(false);
        linhaSelecionada = selecionado;
        cdLaboratorio = cdLaboratorio;
        model = mtb; 
        
        LaboratorioController mc = new LaboratorioController();
        Laboratorio f = new Laboratorio();
        f = mc.listarLaboratorioById(cdLaboratorio);
        
        campoCodigo.setText(Integer.toString(f.getCodigo()));
        
        carregarCombo(f.getProfessor().getCodigo());
        Date dataTemp = new Date();
        SimpleDateFormat formataData = new SimpleDateFormat("dd/MM/yyyy");
        String data = formataData.format(f.getReserva());
        compoReserva.setText(data);
        
        compoTurno.setSelectedItem(f.getTurno());
        compoAula.setSelectedItem(f.getAula());
    
    

       
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CompoNome = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        compoReserva = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        compoTurno = new javax.swing.JComboBox();
        BotaoSalvar = new javax.swing.JToggleButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        compoAula = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Reserva do Laboratorio");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel1.setText("Código");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 110, 60, 20);

        campoCodigo.setEditable(false);
        campoCodigo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        campoCodigo.setToolTipText("Digite o nome do usuário");
        campoCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCodigoActionPerformed(evt);
            }
        });
        jPanel1.add(campoCodigo);
        campoCodigo.setBounds(50, 150, 120, 30);

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel3.setText("Nome do Professor");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(200, 110, 160, 20);

        CompoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompoNomeActionPerformed(evt);
            }
        });
        jPanel1.add(CompoNome);
        CompoNome.setBounds(200, 150, 360, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Data da Reserva");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 210, 140, 17);

        try {
            compoReserva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(compoReserva);
        compoReserva.setBounds(50, 250, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Turno");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 310, 70, 17);

        compoTurno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        compoTurno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Matutino", "Vespertino", "Noturno" }));
        jPanel1.add(compoTurno);
        compoTurno.setBounds(50, 350, 110, 30);

        BotaoSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/isequiel/view/imagens/SalvarUsuario.png"))); // NOI18N
        BotaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(BotaoSalvar);
        BotaoSalvar.setBounds(560, 360, 100, 90);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Salvar");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(580, 460, 90, 22);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setText("Editar Reserva Laboratório");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(260, 40, 310, 28);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Aula");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 410, 25, 17);

        compoAula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        compoAula.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1º", "2º", "3º", "4º", "5º" }));
        jPanel1.add(compoAula);
        compoAula.setBounds(50, 450, 50, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCodigoActionPerformed

    private void CompoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompoNomeActionPerformed
  
    }//GEN-LAST:event_CompoNomeActionPerformed

    private void BotaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoSalvarActionPerformed
       Laboratorio f = new Laboratorio();
      
       
         f.setProfessor((Professor)CompoNome.getSelectedItem());
        try {
            f.setReserva(new SimpleDateFormat("dd/MM/yyyy").parse(compoReserva.getText()));
        } catch (ParseException ex) {
            System.out.println("Erro na conversão de datas" + ex.getMessage());
        }
        f.setTurno(compoTurno.getSelectedItem().toString());
        f.setAula(compoAula.getSelectedItem().toString());
        f.setCodigo(Integer.parseInt(campoCodigo.getText())); 
        
       LaboratorioController mc = new LaboratorioController();
            if (mc.salvar(f)){
            model.updateLaboratorio(linhaSelecionada, f);
            }
            dispose();
        
    }//GEN-LAST:event_BotaoSalvarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotaoSalvar;
    private javax.swing.JComboBox CompoNome;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JComboBox compoAula;
    private javax.swing.JFormattedTextField compoReserva;
    private javax.swing.JComboBox compoTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables


 private void carregarCombo(int cdProfessor) {
         //assim como é feito numa JTable, temos o DefaultComboBoxModel que é o model do JComboBox
        DefaultComboBoxModel comboModel = (DefaultComboBoxModel) CompoNome.getModel();
        //removendo todos os elementos do combo
        comboModel.removeAllElements();
        //cria a lista: java.util.List
        List<Professor> professores = new ArrayList<Professor>();
        ProfessorController a = new ProfessorController();
        professores = a.listarProfessor();
        
     
        for (int linha = 0; linha < professores.size(); linha++) {
            //pegando a categoria da lista
            Professor professor = professores.get(linha);
            //adicionando a categoria no combo
            comboModel.addElement(professor);
            if ( professor.getCodigo()== cdProfessor){
                comboModel.setSelectedItem(professor);
            }
            
        }     
 }
}